spring.application.name=limits-service
project.file=file/

limits-service.minimum=1
limits-service.maximum=9999

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
